const catalog={
ems:{title:'MedLink',accent:'#58d8d8',description:'An EMS-only response handset built around medics, scene triage, patient transfers and medical command. Clean clinical displays meet rugged field equipment.',tags:['EMS ONLY','TRIAGE DISPATCH','MEDIC STATUS','MAYDAY']},
police:{title:'BlueLine',accent:'#73acff',description:'An officer-only tactical radio for patrol, pursuits and command. Dedicated law-enforcement frequencies and a CAD call board keep the response coordinated.',tags:['POLICE ONLY','CAD DISPATCH','TACTICAL BANDS','PANIC ALERT']},
gang:{title:'BlackWire',accent:'#c79bff',description:'A burner handset for crews and underground operations. Break a police signal through three tuning stages, then manage an RF dead zone from your radio.',tags:['CREW / BURNER ACCESS','POLICE SCANNER','RF JAMMER','BACKUP']},
zombie:{title:'Dead Air',accent:'#d9bd77',description:'A weathered survivor relay for the full apocalypse. Track your squad, check field medical status and coordinate rescues, supply runs and infected breaches.',tags:['SURVIVOR NETWORK','WASTELAND DISPATCH','SQUAD STATUS','BEACONS']}
};
let chosen='ems';const iframe=document.getElementById('radio-preview');
const choose=kind=>{if(!catalog[kind])kind='ems';chosen=kind;for(const id of ['frame-select','theme-select','page-select'])document.getElementById(id).innerHTML='';const c=catalog[kind];document.documentElement.style.setProperty('--accent',c.accent);document.querySelectorAll('[data-radio]').forEach(b=>b.classList.toggle('active',b.dataset.radio===kind));document.getElementById('radio-title').textContent=c.title;document.getElementById('radio-description').textContent=c.description;document.getElementById('feature-tags').innerHTML=c.tags.map(t=>`<span>${t}</span>`).join('');document.getElementById('network-label').textContent=c.tags[0];document.getElementById('stage-label').textContent=`${c.title.toUpperCase()} / LIVE PREVIEW`;document.getElementById('preview-status').textContent='Select a page on the radio to begin.';iframe.title=`Interactive ${c.title} radio preview`;iframe.src=`${kind}/index.html`;history.replaceState({},'',`?radio=${kind}`);};
document.querySelectorAll('[data-radio]').forEach(b=>b.onclick=()=>choose(b.dataset.radio));
const preview=()=>iframe.contentWindow.RadioSuitePreview;
iframe.onload=()=>{const api=preview();if(!api)return;const frame=document.getElementById('frame-select'),theme=document.getElementById('theme-select'),page=document.getElementById('page-select');frame.innerHTML=api.frames.map(f=>`<option value="${f.id}">${f.label}</option>`).join('');theme.innerHTML=api.definitions.themes.map(t=>`<option value="${t[0]}">${t[1]}</option>`).join('');page.innerHTML=[...iframe.contentDocument.querySelectorAll('[data-tab]')].map(b=>`<option value="${b.dataset.tab}">${b.textContent.trim()}</option>`).join('');const s=api.getState();api.center();frame.value=s.profile.frame;theme.value=s.profile.suiteTheme||'one';document.getElementById('font-select').value=s.profile.suiteFont||'sans';document.getElementById('text-size').value=s.profile.fontSize||100;document.getElementById('text-label').textContent=`${s.profile.fontSize||100}%`;};
document.getElementById('frame-select').onchange=e=>preview()?.setProfile({frame:e.target.value});
document.getElementById('theme-select').onchange=e=>preview()?.applyTheme(e.target.value);
document.getElementById('page-select').onchange=e=>preview()?.setTab(e.target.value);
document.getElementById('font-select').onchange=e=>preview()?.setProfile({suiteFont:e.target.value});
document.getElementById('text-size').oninput=e=>{document.getElementById('text-label').textContent=`${e.target.value}%`;preview()?.setProfile({fontSize:Number(e.target.value)});};
document.getElementById('reopen').onclick=()=>iframe.contentWindow.postMessage({type:'radio-preview-reopen'},location.origin);
window.addEventListener('message',e=>{if(e.source===iframe.contentWindow&&e.data?.type==='radio-preview-status')document.getElementById('preview-status').textContent=e.data.message;});
choose(new URLSearchParams(location.search).get('radio')||'ems');
