
const {styles,colors,previewMarkup}=RSTabletFrames;
const assets='preview/',iconCatalog=[{"id": "phone", "label": "Tablet Calls", "file": "phone.png"}, {"id": "messages", "label": "Messages", "file": "messages.png"}, {"id": "email", "label": "Email", "file": "email.png"}, {"id": "contacts", "label": "Contacts", "file": "contacts.png"}, {"id": "survivorchat", "label": "Survivor Chat", "file": "survivorchat.png"}, {"id": "videocall", "label": "Video Call", "file": "videocall.png"}, {"id": "camera", "label": "Camera", "file": "camera.png"}, {"id": "gallery", "label": "Photos", "file": "gallery.png"}, {"id": "recon", "label": "Recon Center", "file": "recon.png"}, {"id": "dispatch", "label": "Dispatch", "file": "dispatch.png"}, {"id": "cctv", "label": "CCTV", "file": "cctv.png"}, {"id": "community", "label": "Community", "file": "chirp.png"}, {"id": "news", "label": "News", "file": "news.png"}, {"id": "mediahub", "label": "Media", "file": "mediahub.png"}, {"id": "bank", "label": "Bank", "file": "bank.png"}, {"id": "bills", "label": "Bills", "file": "bills.png"}, {"id": "garage", "label": "Garage", "file": "garage.png"}, {"id": "racing", "label": "Stats", "file": "racing.png"}, {"id": "races", "label": "Races", "file": "races.png"}, {"id": "market", "label": "Market", "file": "market.png"}, {"id": "work", "label": "Work", "file": "work.png"}, {"id": "yellowpage", "label": "Directory", "file": "yellowpage.png"}, {"id": "taxi", "label": "Taxi", "file": "taxi.png"}, {"id": "houses", "label": "Houses", "file": "houses.png"}, {"id": "darkmarket", "label": "DarkMarket", "file": "darkmarket.png"}, {"id": "maps", "label": "Maps", "file": "maps.png"}, {"id": "radio", "label": "Radio", "file": "radio.png"}, {"id": "drone", "label": "Drone", "file": "drone.png"}, {"id": "scanner", "label": "Scanner", "file": "scanner.png"}, {"id": "vehiclelab", "label": "Vehicle Lab", "file": "vehiclelab.png"}, {"id": "notes", "label": "Notes", "file": "notes.png"}, {"id": "calculator", "label": "Calculator", "file": "calculator.png"}, {"id": "weather", "label": "Weather", "file": "weather.png"}, {"id": "reminders", "label": "Reminders", "file": "reminders.png"}, {"id": "sos", "label": "SOS", "file": "sos.png"}, {"id": "buildertools", "label": "Builder Tools", "file": "buildertools.png"}, {"id": "games", "label": "Arcade", "file": "games.png"}, {"id": "store", "label": "App Store", "file": "store.png"}, {"id": "settings", "label": "Settings", "file": "settings.png"}, {"id": "clock", "label": "Clock", "file": "clock.svg"}, {"id": "calendar", "label": "Calendar", "file": "calendar.svg"}, {"id": "compass", "label": "Compass", "file": "compass.svg"}, {"id": "files", "label": "Files", "file": "files.svg"}];
const finish=document.getElementById('finish');finish.innerHTML=colors.map(c=>`<option value="${c.id}">${c.label}</option>`).join('');finish.value='vice';
function device(s,c,prefix){return `<div class="device">${previewMarkup(s.id,c.id,prefix).replaceAll('img/',assets+'img/')}</div>`;}
function render(){const c=colors.find(c=>c.id===finish.value);document.getElementById('frames').innerHTML=styles.map((s,i)=>`<article class="frame-card">${device(s,c,'collection-'+i)}<div class="frame-copy"><small>${String(i+1).padStart(2,'0')} / THE COLLECTION</small><h3>${s.label}</h3><p>${s.desc}</p><span>${c.label}</span></div></article>`).join('');}
finish.onchange=render;render();
let matrixLoaded=false;document.getElementById('combinations').addEventListener('toggle',()=>{if(matrixLoaded)return;matrixLoaded=true;document.getElementById('matrix').innerHTML=styles.flatMap((s,i)=>colors.map((c,j)=>`<article class="mini">${device(s,c,'matrix-'+i+'-'+j)}<b>${s.label}</b><span>${c.label}</span></article>`)).join('');});
function renderIcons(){const theme=document.getElementById('icon-theme').value;document.getElementById('icons').innerHTML=iconCatalog.map(a=>`<div class="icon-cell"><img src="${assets}img/icon-themes/${theme}/${a.file}" alt=""><span>${a.label}</span></div>`).join('');}document.getElementById('icon-theme').onchange=renderIcons;renderIcons();
